name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v2
    - name: git config
      run: |
        git config --global user.email "zander@xargs.io"
        git config --global user.name "Zander Hill"
    - run: ./bin/setup
    - run: ./bin/deploy
      env:
        GIT_USER: ${{ github.actor }}:${{ github.token }}

